package utils

object Colours {
    private const val COLOUR_START = "\u001b["
    private const val FOREGROUND = COLOUR_START + "3"
    const val FOREGROUND_RESET = COLOUR_START + "0m"

    const val FOREGROUND_BLACK = COLOUR_START + "30m"
    const val FOREGROUND_RED = COLOUR_START + "31m"
    const val FOREGROUND_GREEN = COLOUR_START + "32m"
    const val FOREGROUND_YELLOW = COLOUR_START + "33m"
    const val FOREGROUND_BLUE = COLOUR_START + "34m"
    const val FOREGROUND_MAGENTA = COLOUR_START + "35m"
    const val FOREGROUND_CYAN = COLOUR_START + "36m"
    const val FOREGROUND_WHITE = COLOUR_START + "37m"

    const val FOREGROUND_BLACK_BRIGHT = COLOUR_START + "30;1m"
    const val FOREGROUND_RED_BRIGHT = COLOUR_START + "31;1m"
    const val FOREGROUND_GREEN_BRIGHT = COLOUR_START + "32;1m"
    const val FOREGROUND_YELLOW_BRIGHT = COLOUR_START + "33;1m"
    const val FOREGROUND_BLUE_BRIGHT = COLOUR_START + "34;1m"
    const val FOREGROUND_MAGENTA_BRIGHT = COLOUR_START + "35;1m"
    const val FOREGROUND_CYAN_BRIGHT = COLOUR_START + "36;1m"
    const val FOREGROUND_WHITE_BRIGHT = COLOUR_START + "37;1m"

    const val BACKGROUND_BLACK = COLOUR_START + "40m"
    const val BACKGROUND_RED = COLOUR_START + "41m"
    const val BACKGROUND_GREEN = COLOUR_START + "42m"
    const val BACKGROUND_YELLOW = COLOUR_START + "43m"
    const val BACKGROUND_BLUE = COLOUR_START + "44m"
    const val BACKGROUND_MAGENTA = COLOUR_START + "45m"
    const val BACKGROUND_CYAN = COLOUR_START + "46m"
    const val BACKGROUND_WHITE = COLOUR_START + "47m"

    const val BACKGROUND_BLACK_BRIGHT = COLOUR_START + "40;1m"
    const val BACKGROUND_RED_BRIGHT = COLOUR_START + "41;1m"
    const val BACKGROUND_GREEN_BRIGHT = COLOUR_START + "42;1m"
    const val BACKGROUND_YELLOW_BRIGHT = COLOUR_START + "43;1m"
    const val BACKGROUND_BLUE_BRIGHT = COLOUR_START + "44;1m"
    const val BACKGROUND_MAGENTA_BRIGHT = COLOUR_START + "45;1m"
    const val BACKGROUND_CYAN_BRIGHT = COLOUR_START + "46;1m"
    const val BACKGROUND_WHITE_BRIGHT = COLOUR_START + "47;1m"


}