package utils

object Colours {
    private const val COLOUR_START = "\u001b["
    private const val FOREGROUND = COLOUR_START + "3"
    const val FOREGROUND_RESET = COLOUR_START + "0m"

    const val FOREGROUND_BLACK = FOREGROUND + "0m"
    const val FOREGROUND_RED = FOREGROUND + "1m"
    const val FOREGROUND_GREEN = FOREGROUND + "2m"
    const val FOREGROUND_YELLOW = FOREGROUND + "3m"
    const val FOREGROUND_BLUE = FOREGROUND + "4m"
    const val FOREGROUND_MAGENTA = FOREGROUND + "5m"
    const val FOREGROUND_CYAN = FOREGROUND + "6m"
    const val FOREGROUND_WHITE = FOREGROUND + "7m"

    const val FOREGROUND_BLACK_BRIGHT = FOREGROUND + "0;1m"
    const val FOREGROUND_RED_BRIGHT = FOREGROUND + "1;1m"
    const val FOREGROUND_GREEN_BRIGHT = FOREGROUND + "2;1m"
    const val FOREGROUND_YELLOW_BRIGHT = FOREGROUND + "3;1m"
    const val FOREGROUND_BLUE_BRIGHT = FOREGROUND + "4;1m"
    const val FOREGROUND_MAGENTA_BRIGHT = FOREGROUND + "5;1m"
    const val FOREGROUND_CYAN_BRIGHT = FOREGROUND + "6;1m"
    const val FOREGROUND_WHITE_BRIGHT = FOREGROUND + "7;1m"

    const val BACKGROUND_BLACK = COLOUR_START + "40m"
    const val BACKGROUND_RED = COLOUR_START + "41m"
    const val BACKGROUND_GREEN = COLOUR_START + "42m"
    const val BACKGROUND_YELLOW = COLOUR_START + "43m"
    const val BACKGROUND_BLUE = COLOUR_START + "44m"
    const val BACKGROUND_MAGENTA = COLOUR_START + "45m"
    const val BACKGROUND_CYAN = COLOUR_START + "46m"
    const val BACKGROUND_WHITE = COLOUR_START + "47m"

    const val BACKGROUND_BLACK_BRIGHT = COLOUR_START + "40;1m"
    const val BACKGROUND_RED_BRIGHT = COLOUR_START + "41;1m"
    const val BACKGROUND_GREEN_BRIGHT = COLOUR_START + "42;1m"
    const val BACKGROUND_YELLOW_BRIGHT = COLOUR_START + "43;1m"
    const val BACKGROUND_BLUE_BRIGHT = COLOUR_START + "44;1m"
    const val BACKGROUND_MAGENTA_BRIGHT = COLOUR_START + "45;1m"
    const val BACKGROUND_CYAN_BRIGHT = COLOUR_START + "46;1m"
    const val BACKGROUND_WHITE_BRIGHT = COLOUR_START + "47;1m"


}