package utils

object Console_Colours {
    private const val COLOUR_START = "\u001b["
    private const val FOREGROUND = COLOUR_START + "3"
    private const val BACKGROUND = COLOUR_START + "4"
    const val FOREGROUND_RESET = COLOUR_START + "0m"

    const val FOREGROUND_BLACK = FOREGROUND + "0m"
    const val FOREGROUND_RED = FOREGROUND + "1m"
    const val FOREGROUND_GREEN = FOREGROUND + "2m"
    const val FOREGROUND_YELLOW = FOREGROUND + "3m"
    const val FOREGROUND_BLUE = FOREGROUND + "4m"
    const val FOREGROUND_MAGENTA = FOREGROUND + "5m"
    const val FOREGROUND_CYAN = FOREGROUND + "6m"
    const val FOREGROUND_WHITE = FOREGROUND + "7m"

    const val FOREGROUND_BLACK_BRIGHT = FOREGROUND + "0;1m"
    const val FOREGROUND_RED_BRIGHT = FOREGROUND + "1;1m"
    const val FOREGROUND_GREEN_BRIGHT = FOREGROUND + "2;1m"
    const val FOREGROUND_YELLOW_BRIGHT = FOREGROUND + "3;1m"
    const val FOREGROUND_BLUE_BRIGHT = FOREGROUND + "4;1m"
    const val FOREGROUND_MAGENTA_BRIGHT = FOREGROUND + "5;1m"
    const val FOREGROUND_CYAN_BRIGHT = FOREGROUND + "6;1m"
    const val FOREGROUND_WHITE_BRIGHT = FOREGROUND + "7;1m"

    const val BACKGROUND_BLACK = BACKGROUND + "0m"
    const val BACKGROUND_RED = BACKGROUND + "1m"
    const val BACKGROUND_GREEN = BACKGROUND + "2m"
    const val BACKGROUND_YELLOW = BACKGROUND + "3m"
    const val BACKGROUND_BLUE = BACKGROUND + "4m"
    const val BACKGROUND_MAGENTA = BACKGROUND + "5m"
    const val BACKGROUND_CYAN = BACKGROUND + "6m"
    const val BACKGROUND_WHITE = BACKGROUND + "7m"

    const val BACKGROUND_BLACK_BRIGHT = BACKGROUND + "0;1m"
    const val BACKGROUND_RED_BRIGHT = BACKGROUND + "1;1m"
    const val BACKGROUND_GREEN_BRIGHT = BACKGROUND + "2;1m"
    const val BACKGROUND_YELLOW_BRIGHT = BACKGROUND + "3;1m"
    const val BACKGROUND_BLUE_BRIGHT = BACKGROUND + "4;1m"
    const val BACKGROUND_MAGENTA_BRIGHT = BACKGROUND + "5;1m"
    const val BACKGROUND_CYAN_BRIGHT = BACKGROUND + "6;1m"
    const val BACKGROUND_WHITE_BRIGHT = BACKGROUND + "7;1m"


}